name: Deploy to CDN
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  upload-to-cdn:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # ratchet:actions/checkout@v5
        with:
          persist-credentials: false

      - name: Upload dependencies to CDN
        uses: nais/deploy/actions/cdn-upload/v2@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # ratchet:nais/deploy/actions/cdn-upload/v2@master
        with:
          team: min-side
          source: ./packages
          destination: tms-shared-dependencies
