name: Deploy to CDN
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  upload-to-cdn:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # ratchet:actions/checkout@v5
        with:
          persist-credentials: false

      - name: Upload dependencies to CDN
        uses: nais/deploy/actions/cdn-upload/v2@c55d6073d913975d2dada508bdfefc6427d39867 # ratchet:nais/deploy/actions/cdn-upload/v2@master
        with:
          team: min-side
          source: ./packages
          destination: tms-shared-dependencies
